language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
# command to install dependencies
install: 
install:
    - sudo apt-get install python-qt4 python-qt4-dev python-sip python-sip-dev
    - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/PyQt4/ $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
    - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/sip.so $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
    - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/sipdistutils.py $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
    - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/sipconfig.py $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
    - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/sipconfig_nd.py $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
    - ls -l $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
    - which python
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
# # command to run tests
script: nosetests
